pipeline {
agent any
stages {
stage ('Git-Clone') {
steps {
checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'priya3019-github', url: 'https://github.com/priya3019/devops-june-2022.git']]])
sh 'pwd'
}


}

stage ('Build-Deploy') {
steps {
script {
sh '''
docker build -t priyappatil/maven /home/ubuntu/devops-june-2022/Docker/app/maven
docker run -it --rm -d -p 8080:8080 --name calc priyappatil/maven
'''
}

}


}

stage ('push-docker-image') {
steps {
script {
withCredentials([string(credentialsId: 'dockerhubid', variable: 'dockerhubpwd')]) {
sh 'docker login -u priyappatil -p ${dockerhubpwd}'
}

sh 'docker push priyappatil/maven'
}
}
}



}
}

